[package]
name = "rabbitmq_consummer_template"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = "2.6.0"
lapin = "=2.5.3"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["macros", "rt"] }
tokio-amqp = "2.0.0"